name: veli_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.5
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.5
  provider:
  google_sign_in: ^6.0.2
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/photos/
    - assets/images/icons/

  fonts:
    - family: Veli_Light
      fonts:
        - asset: assets/fonts/Veli_Light.ttf

    - family: Veli_Regular
      fonts:
        - asset: assets/fonts/Veli_Regular.ttf

    - family: Veli_SemiBold
      fonts:
        - asset: assets/fonts/Veli_SemiBold.ttf

    - family: Veli_Bold
      fonts:
        - asset: assets/fonts/Veli_Bold.ttf

    - family: Veli_Black
      fonts:
        - asset: assets/fonts/Veli_Black.ttf
